### ISSUE TITLE
ImportError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by bpf** [jlinoff/pybld#1]
I get an ImportError when I try to use sqlite3. 

```
~/python/3.5.2/venv/python352/bin$ python
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bpf/python/3.5.2/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/home/bpf/python/3.5.2/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'

$ python
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bpf/python/2.7.12/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/home/bpf/python/2.7.12/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3
```

I roughly followed the instructions [here](https://www.bluebill.net/2016/04/24/install-python-and-sqlite-from-source/) to do a local install of sqlite and link python to it. 

Please consider a pybld option to build a local instance of sqlite and link python to it.

**Comment by jlinoff** [comment]
Thank you for the suggestion. I am looking into it now.

**Comment by jlinoff** [comment]
I have not forgotten this but have been really busy. Will get to it this weekend.

**Comment by jlinoff** [comment]
I finally got a chance to look at this request.

Sadly, in order for the script to install sqlite3 at a system level it would need to know which package manager to use but that knowledge is very system _dependent_.

This script is meant to be as system _independent_ as possible so I am sorry to say that I cannot add that capability without really increasing the complexity of the code and violating the assumption of independence.

To give you some idea of the complexity, here is a list of _some_ of the package managers that I am aware of.

1. linux - apt, dnf, pacman, yasl, yum
2. mac - brew, ports

If you can think of a way to do this in a system independent way, i would be happy to add it but for now I am closing this ticket.
